name: Deploy

on:
  push:
    branches:
      - development
      - master

jobs:
  firebase:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cache-name }}
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm --prefix functions ci

      - name: Install firebase tools
        run: npm i -g firebase-tools

      - name: Use Production
        run: firebase use production --token ${{ secrets.FIREBASE_TOKEN }}
        if: github.ref == 'refs/heads/master'

      - name: Use Staging
        run: firebase use staging --token ${{ secrets.FIREBASE_TOKEN }}
        if: github.ref == 'refs/heads/development'

      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
