name: WIP status
on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  wip:
    name: Set WIP status
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: wip/action@v1.0.0
